### DISCUSSION TITLE
Compatibility with FluidNC

### DISCUSSION THREAD

**Discussion by tiagomelobr** [FYSETC/FYSETC-E4#59] [Q&A]
Hey everyone,

I'm looking for a board for a pen plotter, and I'm considering this one. Have anyone had success with using FluidNC as firmware? Any issues/recommendations?

**Comment by goozoon** [comment]
Looks like yes
https://github.com/jamescarruthers/PlotteRXY/tree/main/Firmware

but i cant figure out how to operate Servo for pen lifter

**Reply by goozoon** [reply]
i see it now:

```
servo:
  pwm_hz: 50
  output_pin: gpio.13
  min_pulse_us: 500
  max_pulse_us: 2500
```

and macro to up/down

```
macros:
  pen_up: M280 P0 S30
  pen_down: M280 P0 S120
```
